#!/usr/bin/env python3
"""Generate lectures/l06/l06-validation.ipynb.

The L6 demo runs on the live Tennessee Eastman stream, the same feed A3 collects
from, so the session's ideas are exercised on data nobody has cleaned and whose
answers nobody knows in advance.

Ten sections, matching the notes:

  1. The plant. What the 53 tags are, against the flowsheet, so a reader knows
     what a reactor level and a product analyser are before validating them.
  2. Collect. paho over WebSockets on 443, ~3 minutes, written down verbatim
     and cached, because a stream is gone once it has gone past.
  3. The contract. The retained birth message: acceleration factor, sample
     interval, and one row per tag with its unit and, for the analysers, the
     interval and dead time.
  4. Decode. Nested JSON to one tidy row per reading, with the three clocks
     parsed and the timestamp resolution pinned.
  5. The schema, generated FROM the contract rather than typed out, and run as a
     gate: one schema for what the feed promised, one for what an average needs.
  6. The confident wrong number, and quarantine. Deduplicating on
     (tag, sourceTimestamp) is what tells you how many measurements you really
     have; the product analysers arrive about five times each.
  7. Three clocks. The contract predicts each tag's maximum event-to-publish
     lag, and the data agrees, for all 53.
  8. Late data and a watermark. What fraction arrives behind the frontier, and
     how long you have to wait to lose none of it.
  9. Long to wide. Pivoting onto the regular sample grid is where the holes
     show up: the analysers hold, so their columns are mostly empty, and a
     forward fill writes about a fifth of the table. Keep a mask.
 10. Windows in event time, against the same windows in publish time.

Design notes so the demo runs cleanly:
  - Every expected failure is caught, so "Restart and Run All" finishes top to
    bottom. The committed .ipynb carries no outputs and uses relative paths only.
  - The capture is cached under data/, which is gitignored, so a second run
    costs nothing and the notebook stays runnable with the plant switched off
    once somebody has a file.
  - Nothing in the markdown quotes a number the run produces, because the run
    produces different numbers every time. The cells print them.

Kept in a generator for deterministic cell ids and no hand-edited JSON.
"""
import json
import sys
from pathlib import Path

OUT = Path(__file__).parent / "l06-validation.ipynb"

_n = 0


def _next_id(kind):
    global _n
    _n += 1
    return f"{kind}-{_n:02d}"


def md(*lines):
    return {"cell_type": "markdown", "id": _next_id("md"),
            "metadata": {}, "source": list(lines)}


def code(*lines):
    return {"cell_type": "code", "id": _next_id("code"), "execution_count": None,
            "metadata": {}, "outputs": [], "source": list(lines)}


FIGURE = "https://kitchingroup.cheme.cmu.edu/f26-06763/_images/tep-screenshot.png"

cells = [
    md("# L6 demo: validating a live plant stream\n",
       "\n",
       "This notebook connects to a running plant, collects a few minutes of its telemetry,\n",
       "and puts that telemetry through the two ideas of this session: a schema used as a\n",
       "gate, and a windowed aggregate computed in event time.\n",
       "\n",
       "The feed is the same one Assignment **A3** collects from, and it is live. Nobody has\n",
       "cleaned it, the numbers are different every time you run this, and some of what\n",
       "arrives is wrong or late. Read the printed output rather than trusting a number\n",
       "written in a markdown cell, because there are none.\n"),

    # ------------------------------------------------------------------ 1
    md("## 1. The plant\n",
       "\n",
       "The [Tennessee Eastman process](https://doi.org/10.1016/0098-1354(93)80018-I) is a\n",
       "chemical plant published by Downs and Vogel in 1993 as a control and monitoring\n",
       "benchmark, and it has been one ever since. Four gaseous reactants (A, C, D, E) plus\n",
       "an inert (B) and a byproduct (F) go in; two liquid products (G and H) come out.\n",
       "\n",
       f"![The Tennessee Eastman process flowsheet]({FIGURE})\n",
       "\n",
       "*Figure from [Lyu, Botcha, Kulkarni, Pagaria, Alves, Sunshine, and Kitchin\n",
       "(2026)](https://chemrxiv.org/doi/abs/10.26434/chemrxiv.10001628/v1). You can run the\n",
       "simulator yourself at [TEP Studio](https://kitchingroup.cheme.cmu.edu/tep-rust/studio/).*\n",
       "\n",
       "Follow the flowsheet left to right. Feeds A, D and E and a combined A/B/C stream\n",
       "enter a **reactor**, which is where the reaction happens and which is cooled by a\n",
       "water coil. Its vapour goes to a **condenser**, then to a **separator** that splits\n",
       "the condensed liquid from the gas. The gas is recycled through a **compressor** back\n",
       "to the reactor, with a small **purge** stream bleeding off so the inert B does not\n",
       "accumulate until the plant chokes. The separator's liquid drops into a **stripper**,\n",
       "which boils the light components back out with steam, and what leaves the bottom of\n",
       "the stripper is the product.\n",
       "\n",
       "Three blocks on the diagram are labelled Analyzer, on the reactor feed, on the purge\n",
       "and on the product. Those are gas chromatographs, and they are the reason this plant\n",
       "is interesting to a streaming lecture: they do not report continuously. They take a\n",
       "sample, run it, and report a composition some minutes later, so their readings are\n",
       "both infrequent and stale by a known amount.\n",
       "\n",
       "The stream carries 53 tags, which is the whole instrument list:\n",
       "\n",
       "| Tags | What they are |\n",
       "|---|---|\n",
       "| `XMEAS_1` to `XMEAS_6` | feed flows and the recycle, in kscmh or kg/hr |\n",
       "| `XMEAS_7` to `XMEAS_9` | reactor pressure, level, temperature |\n",
       "| `XMEAS_10` | purge rate |\n",
       "| `XMEAS_11` to `XMEAS_14` | separator temperature, level, pressure, underflow |\n",
       "| `XMEAS_15` to `XMEAS_19` | stripper level, pressure, underflow, temperature, steam |\n",
       "| `XMEAS_20` to `XMEAS_22` | compressor work and the two cooling water outlets |\n",
       "| `XMEAS_23` to `XMEAS_28` | reactor feed composition, A to F, from an analyser |\n",
       "| `XMEAS_29` to `XMEAS_36` | purge composition, A to H, from an analyser |\n",
       "| `XMEAS_37` to `XMEAS_41` | product composition, D to H, from an analyser |\n",
       "| `XMV_1` to `XMV_12` | the twelve valve positions the controller writes |\n",
       "\n",
       "So 34 of the 53 are continuous instruments, sampled and reported every cycle, and 19\n",
       "are analyser channels that report on their own slower schedule. Section 7 measures\n",
       "that split from the data instead of taking this paragraph's word for it.\n"),

    # ------------------------------------------------------------------ 2
    md("## 2. Collect from the live stream\n",
       "\n",
       "The plant publishes to an MQTT broker over WebSockets on port 443, which is the one\n",
       "port that is open everywhere. Three topics: `plant/tep/birth` carries the tag\n",
       "dictionary and is retained, so you get it the moment you subscribe; `plant/tep/telemetry`\n",
       "carries the readings; `plant/tep/event` carries plant restarts.\n",
       "\n",
       "The cell below does the one thing a collector should do, which is write down exactly\n",
       "what arrived, in the order it arrived, wrapped in an envelope recording when your\n",
       "machine saw it. It does not sort, deduplicate, drop, or parse. Those are decisions,\n",
       "and decisions belong in the pipeline where you can see and test them.\n",
       "\n",
       "The file is cached under `data/`, so running this notebook a second time costs\n",
       "nothing and works with the plant switched off. Delete the file to collect afresh.\n"),
    code("import datetime\n",
         "import json\n",
         "import pathlib\n",
         "import time\n",
         "\n",
         "import paho.mqtt.client as mqtt\n",
         "\n",
         'HOST, PORT, WS_PATH = "kitchin-services.cheme.cmu.edu", 443, "/mqtt"\n',
         'TOPIC = "plant/#"\n',
         "SECONDS = 180\n",
         'RAW = pathlib.Path("data") / "l06-stream.ndjson"\n',
         "\n",
         "\n",
         "def collect(seconds=SECONDS, out=RAW):\n",
         '    """Append one line per message for `seconds`, then stop."""\n',
         "    out.parent.mkdir(parents=True, exist_ok=True)\n",
         '    handle = out.open("a", encoding="utf-8")\n',
         "    count = 0\n",
         "\n",
         "    def on_connect(client, userdata, flags, reason_code, properties=None):\n",
         "        client.subscribe(TOPIC, qos=0)\n",
         "\n",
         "    def on_message(client, userdata, msg):\n",
         "        nonlocal count\n",
         "        # The payload goes through byte for byte. Parsing and re-serializing it\n",
         "        # here would reorder keys and change spacing, and anything computed over\n",
         "        # the exact bytes the broker sent would stop matching.\n",
         "        seen = (datetime.datetime.now(datetime.timezone.utc)\n",
         '                .isoformat(timespec="milliseconds").replace("+00:00", "Z"))\n',
         '        handle.write(\'{"receivedAt":"%s","topic":"%s","payload":%s}\\n\'\n',
         '                     % (seen, msg.topic, msg.payload.decode("utf-8", errors="replace")))\n',
         "        count += 1\n",
         "\n",
         "    client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2, transport=\"websockets\")\n",
         "    client.ws_set_options(path=WS_PATH)\n",
         "    client.tls_set()\n",
         "    client.on_connect, client.on_message = on_connect, on_message\n",
         "    client.connect(HOST, PORT, keepalive=60)\n",
         "    client.loop_start()\n",
         "    time.sleep(seconds)\n",
         "    client.loop_stop()\n",
         "    client.disconnect()\n",
         "    handle.close()\n",
         "    return count\n",
         "\n",
         "\n",
         "if RAW.exists():\n",
         '    print(f"reusing the capture already in {RAW}")\n',
         "else:\n",
         '    print(f"collecting for {SECONDS} s ...")\n',
         '    print(f"{collect()} messages")\n',
         "\n",
         "lines = RAW.read_text().splitlines()\n",
         'print(f"{len(lines)} lines, {RAW.stat().st_size / 1e6:.2f} MB")\n',
         "print(lines[0][:220])"),

    # ------------------------------------------------------------------ 3
    md("## 3. The contract: the birth message\n",
       "\n",
       "A stream of numbers with no dictionary is undecodable, so the publisher sends one\n",
       "**birth message** at startup and the broker retains it. It says how fast the\n",
       "simulation runs against wall clock, when plant time started, how often a sample is\n",
       "taken, and what every tag is.\n",
       "\n",
       "That message is the **data contract** for this feed. Section 5 builds the validation\n",
       "schema out of it rather than typing the same facts a second time, which is the point\n",
       "of having a contract at all: two hand-written copies of the truth will disagree, and\n",
       "the one you are not looking at is the one that is wrong.\n"),
    code("import pandas as pd\n",
         "\n",
         "messages = [json.loads(line) for line in lines]\n",
         'birth = next(m["payload"] for m in messages if m["payload"].get("type") == "birth")\n',
         'telemetry = [m for m in messages if m["topic"].endswith("/telemetry")]\n',
         "\n",
         'print({k: v for k, v in birth.items() if k != "tags"})\n',
         'print(f"{len(birth[\'tags\'])} tags, {len(telemetry)} telemetry messages")\n',
         "\n",
         'contract = pd.DataFrame(birth["tags"]).rename(columns={"name": "tag"})\n',
         '# A capture short enough to miss every analyser refresh would have no such\n',
         '# column at all, and the code below expects one either way.\n',
         'for column in ("analyserIntervalHours", "deadTimeHours"):\n',
         "    if column not in contract:\n",
         "        contract[column] = pd.NA\n",
         "contract"),
    code("# The units the contract declares, and how many tags carry each. The schema in\n",
         "# section 5 keys its range checks on exactly this list.\n",
         'print(contract.groupby("unit").size().sort_values(ascending=False).to_string())\n',
         "\n",
         "# The analyser channels announce themselves: an interval and a dead time, both\n",
         "# in plant hours. Everything else reports every cycle.\n",
         'analysers = contract[contract["analyserIntervalHours"].notna()]\n',
         'print(f"\\n{len(analysers)} analyser channels, {len(contract) - len(analysers)} continuous")\n',
         'print(analysers.groupby(["analyserIntervalHours", "deadTimeHours"]).size().to_string())'),

    # ------------------------------------------------------------------ 4
    md("## 4. Decode: nested JSON to a tidy table\n",
       "\n",
       "Each telemetry message is one sample of the whole plant: an envelope with a sequence\n",
       "number, a publish timestamp and an `isHistorical` flag, wrapping an array of 53\n",
       "metrics. Each metric is an OPC UA `DataValue`, which is a value plus a status code\n",
       "plus the timestamp of the reading itself.\n",
       "\n",
       "So there are **three clocks** on every row, and they answer three different questions:\n",
       "\n",
       "- `sourceTimestamp`, the **event time**, when the instrument took the reading.\n",
       "- `timestamp`, the **publish time**, when the historian put the message on the wire.\n",
       "- `receivedAt`, the **processing time**, when your machine saw it.\n",
       "\n",
       "`pd.json_normalize` flattens one level and copies the envelope fields down onto every\n",
       "metric, which is what `record_path` and `meta` do. Note that the `meta` columns come\n",
       "back as `object`, so `isHistorical` is Python `bool` in an object column rather than a\n",
       "boolean dtype, and has to be cast.\n"),
    code("records = [{\"receivedAt\": m[\"receivedAt\"], **m[\"payload\"]} for m in telemetry]\n",
         "df = pd.json_normalize(\n",
         '    records,\n',
         '    record_path="metrics",\n',
         '    meta=["seq", "timestamp", "isHistorical", "receivedAt"],\n',
         ")\n",
         'df = df.rename(columns={"name": "tag", "statusCode": "status",\n',
         '                        "sourceTimestamp": "event_time", "timestamp": "server_time",\n',
         '                        "receivedAt": "received_at", "isHistorical": "is_historical"})\n',
         "\n",
         "# Pin the timestamp resolution rather than taking the default. pandas 2 parses to\n",
         "# nanoseconds and pandas 3 to microseconds, so a schema that names a dtype passes\n",
         "# on one machine and fails on the next. The wire format is milliseconds.\n",
         'STAMP = "datetime64[ms, UTC]"\n',
         'for column in ("event_time", "server_time", "received_at"):\n',
         '    df[column] = pd.to_datetime(df[column], utc=True, format="ISO8601").astype(STAMP)\n',
         'df["is_historical"] = df["is_historical"].astype(bool)\n',
         'df["seq"] = df["seq"].astype(int)\n',
         "\n",
         "# The unit comes from the contract, not from the telemetry, which never repeats it.\n",
         'df = df.merge(contract[["tag", "unit"]], on="tag", how="left")\n',
         "\n",
         'print(f"{len(df):,} readings from {len(telemetry):,} messages")\n',
         "print(df.dtypes.to_string())\n",
         "df.head()"),

    # ------------------------------------------------------------------ 5
    md("## 5. A schema built from the contract, used as a gate\n",
       "\n",
       "Two schemas, because there are two different questions and conflating them is how a\n",
       "validation suite ends up rejecting data it should have kept.\n",
       "\n",
       "`feed_schema` asks **did the publisher keep its promises**: every tag is one the\n",
       "contract declared, every status is one of the three OPC UA codes, every value that is\n",
       "present is inside the physical range for its unit, and nothing was published before it\n",
       "was measured. A failure here is a bug on the other side of the wire.\n",
       "\n",
       "`clean_schema` asks **is this fit to average**: a real value, a `Good` status, and one\n",
       "row per tag per reading. A failure here is normal and expected, and the answer is not\n",
       "to reject the feed, it is to route the offending rows somewhere else, which section 6\n",
       "does.\n",
       "\n",
       "Both are generated from `contract`. The tag set, the unit list and the allowed\n",
       "statuses are read out of the birth message, so if the plant adds an instrument\n",
       "tomorrow the schema knows about it, and if it adds a unit nobody has written a range\n",
       "for, the assertion below fails loudly instead of waving the values through.\n"),
    code("import pandera.pandas as pa\n",
         "\n",
         "# Physical bounds per unit, wide enough that a plausible reading passes and an\n",
         "# impossible one does not. A composition outside 0 to 100 mole % is not a\n",
         "# measurement, it is an artifact of whatever produced it.\n",
         "UNIT_RANGE = {\n",
         '    "Mole %": (0.0, 100.0),\n',
         '    "%": (0.0, 100.0),\n',
         '    "Deg C": (0.0, 200.0),\n',
         '    "kPa gauge": (0.0, 4000.0),\n',
         '    "kscmh": (0.0, 200.0),\n',
         '    "kg/hr": (0.0, 20000.0),\n',
         '    "m3/hr": (0.0, 200.0),\n',
         '    "kW": (0.0, 2000.0),\n',
         "}\n",
         'unknown = sorted(set(contract["unit"]) - set(UNIT_RANGE))\n',
         'assert not unknown, f"the contract declares a unit with no range here: {unknown}"\n',
         "\n",
         'STATUSES = {"Good", "Uncertain_SensorNotAccurate", "Bad_DeviceFailure"}\n',
         "\n",
         "\n",
         "def in_unit_range(frame):\n",
         '    """One range per unit, so this is a whole-frame check, not a column check."""\n',
         '    low = frame["unit"].map(lambda u: UNIT_RANGE[u][0])\n',
         '    high = frame["unit"].map(lambda u: UNIT_RANGE[u][1])\n',
         '    return frame["value"].isna() | frame["value"].between(low, high)\n',
         "\n",
         "\n",
         "def read_before_published(frame):\n",
         '    """Clock drift check: nothing can be sent before it was measured."""\n',
         '    return frame["event_time"] <= frame["server_time"]\n',
         "\n",
         "\n",
         "COLUMNS = {\n",
         '    "tag": pa.Column(str, pa.Check.isin(set(contract["tag"]))),\n',
         '    "value": pa.Column(float, nullable=True),\n',
         '    "status": pa.Column(str, pa.Check.isin(STATUSES)),\n',
         '    "event_time": pa.Column(STAMP),\n',
         '    "server_time": pa.Column(STAMP),\n',
         '    "received_at": pa.Column(STAMP),\n',
         '    "seq": pa.Column(int, pa.Check.in_range(0, 255)),\n',
         '    "is_historical": pa.Column(bool),\n',
         '    "unit": pa.Column(str, pa.Check.isin(set(UNIT_RANGE))),\n',
         "}\n",
         "CHECKS = [\n",
         '    pa.Check(in_unit_range, name="value_inside_the_range_for_its_unit"),\n',
         '    pa.Check(read_before_published, name="event_time_at_or_before_server_time"),\n',
         "]\n",
         "\n",
         "# strict=True rejects a column nobody declared, which is how a silently added\n",
         "# field gets noticed instead of ignored.\n",
         "feed_schema = pa.DataFrameSchema(COLUMNS, checks=CHECKS, strict=True)"),
    md("Run the feed gate first, non-lazily. It stops at the first problem it meets, which\n",
       "is what a gate in a pipeline should do: fail before the transform stage, not after.\n",
       "\n",
       "Whether it fails depends on what the plant did while you were listening. The\n",
       "simulator occasionally emits a composition a hair below zero, which is physically\n",
       "impossible and a good example of the kind of thing a range check exists to catch.\n"),
    code("try:\n",
         "    feed_schema.validate(df)\n",
         '    print("the feed kept its contract")\n',
         "except pa.errors.SchemaError as err:\n",
         '    print("the feed broke its contract\\n")\n',
         "    print(str(err)[:600])"),
    md("Now the same idea with `lazy=True`, on the stricter schema. Lazy validation collects\n",
       "every failure instead of raising on the first, so `err.failure_cases` is a dataframe\n",
       "you can group and count. That is the difference between \"something is wrong\" and\n",
       "\"here are the four things that are wrong, and how many rows each one accounts for\".\n"),
    code("clean_schema = pa.DataFrameSchema(\n",
         "    dict(COLUMNS,\n",
         "         value=pa.Column(float, nullable=False),\n",
         '         status=pa.Column(str, pa.Check.equal_to("Good"))),\n',
         "    checks=CHECKS,\n",
         '    unique=["tag", "event_time"],\n',
         "    strict=True,\n",
         ")\n",
         "\n",
         "try:\n",
         "    clean_schema.validate(df, lazy=True)\n",
         '    print("every reading is fit to average, which would be a first")\n',
         "except pa.errors.SchemaErrors as err:\n",
         "    cases = err.failure_cases\n",
         '    print(f"{len(cases):,} failure cases over {len(df):,} readings\\n")\n',
         '    print(cases.groupby("check").size().sort_values(ascending=False).to_string())'),

    # ------------------------------------------------------------------ 6
    md("## 6. The confident wrong number, and quarantine\n",
       "\n",
       "The uniqueness failure is the interesting one, and it is not a bug in the feed.\n",
       "\n",
       "An analyser reports every 0.1 or 0.25 plant hours, but the historian publishes every\n",
       "0.05 hours. Between analyses it republishes the last value it has, with the original\n",
       "`sourceTimestamp` attached, which is exactly right: the tag really does still hold\n",
       "that value, and the timestamp really does say when it was measured. Take the feed at\n",
       "face value, though, and you will believe you have five times as many product\n",
       "composition measurements as you do. Any count, any rate, any \"how much data do I\n",
       "have\", and any model that assumes independent samples inherits that factor.\n",
       "\n",
       "Deduplicating on `(tag, sourceTimestamp)` is what recovers the real number, and it has\n",
       "to happen before anything else in section 8 or the held republishes look like a flood\n",
       "of late data.\n",
       "\n",
       "The two other failures get a different treatment. A `Bad_DeviceFailure` reading has a\n",
       "null value, so it cannot poison a mean, but it also cannot be counted as a\n",
       "measurement. An `Uncertain_SensorNotAccurate` reading is the dangerous one: it carries\n",
       "a perfectly plausible number, and nothing about the number itself tells you the device\n",
       "did not trust it. Dropping either silently would be the worst option, so both go to a\n",
       "**quarantine** table with the reason attached, which is a record you can count, plot\n",
       "and complain about.\n"),
    code("low = df[\"unit\"].map(lambda u: UNIT_RANGE[u][0])\n",
         'high = df["unit"].map(lambda u: UNIT_RANGE[u][1])\n',
         "\n",
         'reason = pd.Series("", index=df.index, dtype=object)\n',
         'reason[~df["value"].between(low, high) & df["value"].notna()] = "outside the range for its unit"\n',
         "# Status last, so a flagged reading is reported as flagged rather than as\n",
         "# out of range, which is the more specific complaint.\n",
         'reason[df["status"] != "Good"] = "the device flagged it: " + df["status"]\n',
         "\n",
         'quarantine = df[reason != ""].assign(reason=reason[reason != ""])\n',
         'kept = df[reason == ""]\n',
         "\n",
         'print(quarantine["reason"].value_counts().to_string())\n',
         'print(f"\\nkept {len(kept):,} of {len(df):,} readings")\n',
         "quarantine.head()"),
    code("readings = kept.drop_duplicates(subset=[\"tag\", \"event_time\"]).copy()\n",
         'print(f"{len(kept):,} rows collapse to {len(readings):,} measurements "\n',
         '      f"({100 * (1 - len(readings) / len(kept)):.1f}% were republished values)\\n")\n',
         "\n",
         'counted = (kept.groupby("tag").size().rename("rows_received").to_frame()\n',
         '           .join(readings.groupby("tag").size().rename("measurements")))\n',
         'counted["published_per_measurement"] = (\n',
         '    counted.rows_received / counted.measurements).round(2)\n',
         'counted = counted.sort_values("published_per_measurement")\n',
         "# The two extremes: a continuous instrument, and a product analyser.\n",
         "pd.concat([counted.head(3), counted.tail(3)])"),
    md("With the flagged and impossible rows quarantined and the republishes collapsed, the\n",
       "clean schema should now pass. That is the shape worth copying: the gate does not\n",
       "decide what to do about bad data, it decides whether the data reaching the next stage\n",
       "is what that stage was promised.\n"),
    code("clean_schema.validate(readings, lazy=True)\n",
         'print(f"{len(readings):,} measurements pass the clean schema")'),

    # ------------------------------------------------------------------ 7
    md("## 7. Three clocks, and the nineteen analysers\n",
       "\n",
       "The gap between event time and publish time is not noise, it is a property of the\n",
       "instrument, and the contract already told you what it is. A tag with an\n",
       "`analyserIntervalHours` of 0.25 reports every 900 plant seconds while the historian\n",
       "publishes every 180, so the value on the wire can be up to 900 minus 180 seconds old\n",
       "before it is refreshed. A continuous tag is never stale at all.\n",
       "\n",
       "That is a prediction, made from the contract alone, for each of the 53 tags. The cell\n",
       "below checks it against the measured lag on the messages that were published live.\n",
       "\n",
       "Staleness is measured on what was published, `kept`, rather than on the deduplicated\n",
       "`readings`. A held value is at its stalest on the last message that carries it, and\n",
       "deduplication keeps the first, so measuring after the collapse would report every\n",
       "analyser as perfectly fresh.\n"),
    code("published = kept.assign(\n",
         '    lag_s=(kept["server_time"] - kept["event_time"]).dt.total_seconds())\n',
         "\n",
         'sample_s = birth["sampleIntervalSeconds"]\n',
         "predicted = contract.assign(\n",
         '    predicted_max_lag_s=(contract["analyserIntervalHours"].astype(float).fillna(0.0)\n',
         "                         * 3600 - sample_s).clip(lower=0)\n",
         ')[["tag", "analyserIntervalHours", "predicted_max_lag_s"]]\n',
         "\n",
         "# Only the live messages: a replayed backlog carries a publish time from when the\n",
         "# link came back, which is a different story and is section 8's.\n",
         'live = published[~published["is_historical"]]\n',
         'observed = live.groupby("tag")["lag_s"].max().rename("observed_max_lag_s")\n',
         "\n",
         'check = predicted.merge(observed, on="tag")\n',
         'agree = int((check["predicted_max_lag_s"] == check["observed_max_lag_s"]).sum())\n',
         'print(f"contract predicts the observed maximum lag for {agree} of {len(check)} tags\\n")\n',
         'print(check.groupby(["analyserIntervalHours", "predicted_max_lag_s",\n',
         '                     "observed_max_lag_s"], dropna=False).size()\n',
         '      .rename("tags").to_string())'),
    md("The replayed messages are the other source of lag, and it is much larger. When the\n",
       "publisher cannot reach the broker it buffers, and when the link returns it drains the\n",
       "backlog alongside the live stream, flagged `isHistorical`. Those messages carry their\n",
       "original `sourceTimestamp` and a publish time from the moment they were finally sent,\n",
       "so the gap between the two measures how long the outage was.\n"),
    code("replayed = published[published[\"is_historical\"]]\n",
         'print(f"{len(replayed):,} of {len(published):,} published readings arrived as "\n',
         '      f"replay ({100 * len(replayed) / len(published):.1f}%)")\n',
         "if len(replayed):\n",
         '    print(f"replay lag, plant minutes: median {replayed.lag_s.median() / 60:.0f}, "\n',
         '          f"max {replayed.lag_s.max() / 60:.0f}")\n',
         'print(f"live lag, plant minutes: median {live.lag_s.median() / 60:.1f}, "\n',
         '      f"max {live.lag_s.max() / 60:.1f}")'),

    # ------------------------------------------------------------------ 8
    md("## 8. Late data, and a watermark\n",
       "\n",
       "A **watermark** is an estimate of the event time up to which everything has arrived.\n",
       "Here it is easy to compute honestly: after each message, the frontier is the newest\n",
       "event time seen so far. A measurement is **late** when it turns up carrying an event\n",
       "time behind the frontier that was already in force when its message landed, because\n",
       "any window covering that event time may already have been closed and reported.\n",
       "\n",
       "The question a watermark actually answers is operational: how long do you agree to\n",
       "wait before declaring a window final. Wait too little and you drop real data; wait too\n",
       "long and every dashboard on the plant is behind. The sweep below prices that choice\n",
       "against this capture, in plant minutes and in the wall clock seconds they correspond\n",
       "to at this acceleration factor.\n"),
    code("frontier = (readings.groupby(\"received_at\")[\"event_time\"].max()\n",
         "            .sort_index().cummax())\n",
         "# The frontier in force *before* this message landed, which is what a window\n",
         "# would have been judged against.\n",
         'readings["watermark_before"] = readings["received_at"].map(frontier.shift())\n',
         'readings["lateness_min"] = (\n',
         '    (readings["watermark_before"] - readings["event_time"])\n',
         "    .dt.total_seconds() / 60).clip(lower=0)\n",
         "\n",
         'late = readings["lateness_min"] > 0\n',
         'print(f"late against the watermark: {int(late.sum()):,} of {len(readings):,} "\n',
         '      f"({100 * late.mean():.1f}%)\\n")\n',
         'print(pd.crosstab(readings["is_historical"], late,\n',
         '                  rownames=["replayed"], colnames=["late"]).to_string())\n',
         "if late.any():\n",
         '    print("\\nlateness in plant minutes:")\n',
         '    print(readings.loc[late, "lateness_min"].describe().to_string())'),
    code("acceleration = birth[\"accelerationFactor\"]\n",
         "rows = []\n",
         "for allowance in (0, 15, 30, 45, 60, 90, 120, 180):\n",
         '    dropped = int((readings["lateness_min"] > allowance).sum())\n',
         '    rows.append({"allowance_plant_min": allowance,\n',
         '                 "your_wall_clock_s": round(allowance * 60 / acceleration, 1),\n',
         '                 "dropped_as_late": dropped,\n',
         '                 "percent_lost": round(100 * dropped / len(readings), 2)})\n',
         "pd.DataFrame(rows)"),

    # ------------------------------------------------------------------ 9
    md("## 9. From long to wide, and the holes that appear\n",
       "\n",
       "Everything so far has been long, one row per reading, which is the shape that lets\n",
       "each row carry its own status and its own timestamp. A correlation, a control chart\n",
       "and a Hotelling statistic are all defined over the other shape: one row per sample\n",
       "instant, one column per tag.\n",
       "\n",
       "The pivot is one line, and the table that comes out is mostly empty. The 53 tags do\n",
       "not share a timestamp grid. A continuous instrument stamps the instant it was\n",
       "sampled; an analyser stamps the instant its last analysis finished, which is an\n",
       "earlier instant on the same 180-second grid. Pivot on `event_time` and the index\n",
       "becomes the union of both sets, with each column present only at its own.\n"),
    code("step = pd.Timedelta(seconds=int(birth[\"sampleIntervalSeconds\"]))\n",
         'grid = pd.date_range(readings["event_time"].min(),\n',
         '                     readings["event_time"].max(), freq=step)\n',
         "\n",
         "wide = (readings\n",
         '        .pivot_table(index="event_time", columns="tag", values="value",\n',
         '                     aggfunc="first")\n',
         "        .reindex(grid)\n",
         '        .reindex(columns=contract["tag"]))\n',
         'wide.index.name = "event_time"\n',
         "\n",
         'print(f"{wide.shape[0]} sample instants x {wide.shape[1]} tags")\n',
         'print(f"empty cells {int(wide.isna().sum().sum())} "\n',
         '      f"({100 * wide.isna().to_numpy().mean():.1f}% of the table)")\n',
         'print(f"rows with no holes at all: {int((~wide.isna().any(axis=1)).sum())}")'),
    md("Split the holes by what caused them, because the two kinds want different answers.\n"),
    code('analyser = contract.loc[contract["analyserIntervalHours"].notna(), "tag"]\n',
         'continuous = contract.loc[contract["analyserIntervalHours"].isna(), "tag"]\n',
         "\n",
         'for label, cols in (("continuous", continuous), ("analyser", analyser)):\n',
         "    block = wide[list(cols)]\n",
         '    print(f"{label:11s} {len(cols):2d} tags, empty "\n',
         '          f"{int(block.isna().sum().sum()):6d} "\n',
         '          f"({100 * block.isna().to_numpy().mean():5.2f}%)")'),
    md("An analyser cell is empty because the instrument has not finished a new analysis.\n",
       "The composition it is reporting between analyses is still the one from the last\n",
       "analysis, so carrying the value forward repeats what the instrument is saying.\n",
       "\n",
       "A continuous cell is empty because a message never arrived. The value moved while\n",
       "nobody was looking, and carrying it forward invents a measurement. Both fills are\n",
       "defensible on a plant dashboard. Neither is defensible if the table that comes out\n",
       "the far end cannot say which cells were measured.\n",
       "\n",
       "So fill it, and keep the mask.\n"),
    code("was_empty = wide.isna()\n",
         "filled = wide.ffill()\n",
         "\n",
         'print(f"filled {int(was_empty.to_numpy().sum())} cells "\n',
         '      f"({100 * was_empty.to_numpy().mean():.1f}% of the table)")\n',
         'print(f"still empty after the fill: {int(filled.isna().sum().sum())} cells in "\n',
         '      f"{int(filled.isna().any(axis=1).sum())} rows")\n',
         "\n",
         'print("\\nthe eight tags we invented the most values for:")\n',
         "print(was_empty.sum().sort_values(ascending=False).head(8).to_string())"),
    md("Anything still empty is at the very start of the grid, where an analyser reported a\n",
       "value stamped before the first continuous sample arrived and there is nothing earlier\n",
       "to carry forward. Drop those rows or back-fill them, and say which you did.\n",
       "\n",
       "`filled` now looks like a complete measurement table, and roughly a fifth of it was\n",
       "written by us rather than by the plant. `was_empty` beside it is what lets the next\n",
       "stage tell the two apart. **A3** asks for the same pair on your own capture, with the\n",
       "two hole counts in your report.\n"),

    # ------------------------------------------------------------------ 10
    md("## 10. Windows in event time\n",
       "\n",
       "Everything above is preparation for one question: what is the average of this tag\n",
       "over the last half hour of plant time. The answer depends on which clock you bucket\n",
       "by, and the two answers are not close.\n",
       "\n",
       "Bucketing by publish time is what you get for free, because it is the order the data\n",
       "arrived in. Bucketing by event time is what the question meant. The cell below\n",
       "computes both, as 30 plant-minute tumbling windows, for one product analyser and one\n",
       "continuous instrument.\n",
       "\n",
       "Watch for two different failures. Some publish-time windows come out **empty**, which\n",
       "is a gap on a dashboard for a period when the plant was running normally and the link\n",
       "was down. Others are simply **wrong**, by an amount worth comparing against the tag's\n",
       "own standard deviation, because readings landed in a neighbouring bucket.\n"),
    code('WINDOW = "30min"\n',
         "\n",
         "\n",
         "def tumbling(tag):\n",
         '    """The same tag, the same window, bucketed by two different clocks."""\n',
         '    one = readings[readings["tag"] == tag]\n',
         "    return pd.concat([\n",
         '        one.set_index("event_time")["value"].resample(WINDOW).mean().rename("by event time"),\n',
         '        one.set_index("server_time")["value"].resample(WINDOW).mean().rename("by publish time"),\n',
         "    ], axis=1)\n",
         "\n",
         "\n",
         'for tag in ("XMEAS_40_product_G", "XMEAS_9_reactor_temperature"):\n',
         "    w = tumbling(tag)\n",
         '    gap = (w["by event time"] - w["by publish time"]).abs()\n',
         '    spread = readings.loc[readings["tag"] == tag, "value"].std()\n',
         '    print(f"{tag}: {len(w)} windows, "\n',
         '          f"{int(w[\'by publish time\'].isna().sum())} empty by publish time, "\n',
         '          f"largest disagreement {gap.max():.4f} against a standard deviation "\n',
         '          f"of {spread:.4f}")\n',
         "\n",
         'tumbling("XMEAS_40_product_G")'),
    code("import matplotlib.pyplot as plt\n",
         "\n",
         'w = tumbling("XMEAS_40_product_G")\n',
         "fig, ax = plt.subplots(figsize=(10, 3.6))\n",
         'ax.step(w.index, w["by event time"], where="post", label="by event time")\n',
         'ax.step(w.index, w["by publish time"], where="post", label="by publish time",\n',
         '        linestyle="--")\n',
         'ax.set_xlabel("plant time")\n',
         'ax.set_ylabel("product G, mole %")\n',
         'ax.set_title("30 plant-minute tumbling windows, one product analyser")\n',
         "ax.legend()\n",
         "fig.autofmt_xdate()\n",
         "fig.tight_layout()"),

    # ------------------------------------------------------------------ end
    md("## What this session leaves you with\n",
       "\n",
       "The feed kept nearly every promise the contract made, and the data still was not fit\n",
       "to average. Those are separate questions, and separating them is most of what a\n",
       "validation suite is for: `feed_schema` catches a publisher that has gone wrong,\n",
       "`clean_schema` catches an assumption the next stage was about to make.\n",
       "\n",
       "The four failures this notebook found are the ones that recur on any real instrument\n",
       "feed. A status code that says the device does not trust its own number, which no\n",
       "amount of looking at the number will reveal. A held value republished on a timer,\n",
       "which inflates every count taken over the raw rows. And data that arrives after the\n",
       "window it belongs to has closed, which is why the aggregate has to be computed in\n",
       "event time and why a watermark is a deadline rather than a fact. And a wide table\n",
       "that is a fifth empty the moment you pivot, because the tags are not sampled on a\n",
       "common grid, which every method defined over complete cases will run into first.\n",
       "\n",
       "Assignment **A3** collects from this same plant, for longer, and asks you to build the\n",
       "pipeline properly: a contract-generated schema, a quarantine you can defend, a filled\n",
       "sample grid that records which of its numbers you invented, and a windowed aggregate\n",
       "whose lateness policy you have to state and justify.\n"),
]

# The Colab bootstrap cell, injected from the notebook's own imports so this
# generator does not carry a second copy of the requirement list. See
# tools/colab_setup.py.
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "tools"))
from colab_setup import with_colab_cell  # noqa: E402

cells = with_colab_cell(cells, OUT)

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.12"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(json.dumps(nb, indent=1) + "\n")
print(f"wrote {OUT} ({len(cells)} cells)")
