#!/usr/bin/env python3
"""Prove tools/derive.py agrees with game/src/seed.ts, vector for vector.

    python tools/check_vectors.py

This is the single most important test in the evidence design, and the reason
is timing. Every other bug here shows up while you are working on it. A
disagreement between the TypeScript and Python derivations shows up when
students start submitting PDFs, all at once, as a wave of REVIEW verdicts
against honest work, and by then the PDFs have already been issued under the
wrong assumption.

The vectors are generated by the TypeScript side (`npm run vectors`) and
replayed here. Deliberately one-directional: if both sides were written from the
same prose description, they could drift together and still look right.

WHAT THIS CATCHES, each confirmed by breaking derive.py on purpose and watching
the run go red:

    a domain separator changed (NUL swapped for a space)
    the RNG consumed in the wrong order (option order before variant)
    the counter serialized little-endian instead of big-endian
    the u32 extracted little-endian instead of big-endian

WHAT IT CANNOT CATCH, and this is worth writing down because the obvious test
for it silently passes:

    a change to the rejection-sampling bound in Rng.below().

Rejection fires with probability (2^32 mod n) / 2^32. For every n this code
actually sees (option counts and variant counts, so n <= ~30) that is between
"never" (n a power of two: exactly 0) and about 1 in 200 million. So a broken
bound produces byte-identical output to a correct one across any feasible number
of vectors, in both languages, and no differential test will ever separate them.

That bound is therefore not a cross-language risk. It is a *bias* property, and
it is checked directly in game/tests/test_derive.py instead. Do not "improve"
this file by adding a vector case aimed at it; the case would pass whether or not
the bound is right, which is worse than no test at all.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from derive import derive, normalize_id, selection_hash  # noqa: E402

VECTORS = Path(__file__).resolve().parent.parent / "game" / "tests" / "vectors.json"


def rebuild_pool(v: dict) -> dict:
    """Reconstruct the synthetic pool the TypeScript generator used."""
    options = [f"opt{j}" for j in range(v["n_options"])]
    pool = {}
    for iid in v["pool_ids"]:
        if v["n_variants"] > 1:
            pool[iid] = {
                "variants": [
                    {"id": f"v{k}", "options": options} for k in range(v["n_variants"])
                ]
            }
        else:
            pool[iid] = {"options": options}
    return pool


def main() -> int:
    if not VECTORS.is_file():
        print(f"::error::{VECTORS} is missing. Run `npm run vectors` in game/.")
        return 1

    data = json.loads(VECTORS.read_text(encoding="utf-8"))
    vectors = data["vectors"]
    failures = []

    for i, v in enumerate(vectors):
        try:
            if normalize_id(v["raw_id"]) != v["andrew_id"]:
                failures.append(
                    f"[{i}] {v['raw_id']!r}: normalize_id gave "
                    f"{normalize_id(v['raw_id'])!r}, TS gave {v['andrew_id']!r}"
                )
                continue

            # `attempt` defaults to 1 only for vectors predating the retake
            # window. A vector file that has it must exercise it, so read it
            # rather than letting the signature default quietly hide a drift.
            got = derive(
                v["raw_id"], v["lecture"], rebuild_pool(v), v["pool_version"], v["k"],
                v.get("attempt", 1),
            )
        except Exception as exc:  # noqa: BLE001
            failures.append(f"[{i}] {v['case']}/{v['raw_id']}: raised {exc!r}")
            continue

        if got != v["served"]:
            # Report the first differing position rather than dumping both
            # lists, because the useful signal is *where* they diverge.
            for pos, (a, b) in enumerate(zip(got, v["served"])):
                if a != b:
                    failures.append(
                        f"[{i}] {v['case']}/{v['andrew_id']}: item {pos} differs\n"
                        f"        python: {a}\n"
                        f"        ts    : {b}"
                    )
                    break
            else:
                failures.append(
                    f"[{i}] {v['case']}/{v['andrew_id']}: length "
                    f"{len(got)} vs {len(v['served'])}"
                )
            continue

        if selection_hash(got) != v["selection_hash"]:
            failures.append(
                f"[{i}] {v['case']}/{v['andrew_id']}: selection_hash "
                f"{selection_hash(got)} vs {v['selection_hash']}"
            )

    if failures:
        for f in failures[:20]:
            print(f"::error::{f}")
        if len(failures) > 20:
            print(f"::error::... and {len(failures) - 20} more")
        print(
            f"\n{len(failures)} of {len(vectors)} vectors disagree. "
            "seed.ts and derive.py have diverged; do not ship until they agree."
        )
        return 1

    cases = sorted({v["case"] for v in vectors})
    ids = sorted({v["andrew_id"] for v in vectors})
    print(
        f"OK: {len(vectors)} vectors agree "
        f"({len(cases)} cases x {len(ids)} ids). "
        "derive.py reproduces seed.ts exactly."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
