#!/usr/bin/env python3
"""Put a "run this first" Colab bootstrap cell at the top of every demo notebook.

WHY. `_config.yml` puts an "Open in Colab" button on every notebook page. Colab
runs the notebook against its own preinstalled environment rather than against
this repo's `uv` lockfile, so a notebook that imports mlflow, duckdb, pandera or
botorch dies on the first import for a student who followed the button. The cell
this script injects installs what is missing, and only what is missing, so
Colab's own NumPy, pandas and torch are left at the versions the session already
has. That matters for L1, whose third planted defect depends on which NumPy is
installed: pinning anything here would defuse it.

The requirement list is DERIVED from the notebook's own imports rather than
written by hand, so a notebook that grows an import gets a corrected cell the
next time this runs. Keeping a hand-written list here would be one more
committed artifact nobody regenerates, which is the failure mode CLAUDE.md
section 9c is about.

Eleven of the notebooks are themselves generated by `lectures/lNN/build_notebook.py`.
Those call `with_colab_cell` before writing, so regenerating one does not silently
drop the cell.

    python3 tools/colab_setup.py --write     # inject or refresh, all notebooks
    python3 tools/colab_setup.py --check     # fail if any cell is missing or stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MD_ID = "colab-setup-md"
CODE_ID = "colab-setup"

# Import name -> pip name, for the packages where the two differ. Anything not
# listed installs under its own import name.
PIP_NAMES = {
    "sklearn": "scikit-learn",
    "psycopg": "psycopg[binary]",
    "faiss": "faiss-cpu",
    "rank_bm25": "rank-bm25",
    "yaml": "pyyaml",
    "dask.dataframe": "dask[dataframe]",
    "pandera.pandas": "pandera",
}

# Submodules worth probing in their own right, because the parent package can be
# installed while the submodule is not: Colab ships dask without the dataframe
# extra, and pandera.pandas exists only from pandera 0.24. Probing the parent
# would report "nothing to install" and then the import cell would fail.
DOTTED = {"dask.dataframe", "pandera.pandas"}

# One extra sentence in the markdown cell, where Colab cannot supply something
# that no amount of pip will fix.
NOTES = {
    "l03-sql-timeseries": (
        "This demo also needs a PostgreSQL server, which Colab does not provide. "
        "Point `L3_DSN` at a database you can reach, or run this one locally."
    ),
}

IMPORT_RE = re.compile(r"^\s*(?:import|from)\s+([\w.]+)", re.M)


def requirements(nb: dict) -> dict[str, str]:
    """The notebook's third-party imports, as {module to probe: pip name}."""
    modules = set()
    for cell in nb["cells"]:
        if cell["cell_type"] == "code":
            modules.update(IMPORT_RE.findall("".join(cell["source"])))

    keys = set()
    for module in modules:
        top = module.split(".")[0]
        if top in sys.stdlib_module_names or top == "google":
            continue
        keys.add(module if module in DOTTED else top)

    # A dotted probe supersedes its parent: probing pandera.pandas already tells
    # us whether pandera is there.
    keys -= {k.split(".")[0] for k in keys if k in DOTTED}
    return {k: PIP_NAMES.get(k, k) for k in sorted(keys)}


def _cells(nb: dict, stem: str) -> list[dict]:
    reqs = requirements(nb)
    note = NOTES.get(stem)

    md = [
        "## Run this first on Colab\n",
        "\n",
        "Colab starts from its own preinstalled environment rather than this course's `uv`\n",
        "environment, so run the cell below before anything else. It installs what this\n",
        "notebook needs and Colab does not already have. Outside Colab it does nothing, so\n",
        "you can run it or skip it.\n",
    ]
    if note:
        md += ["\n", note + "\n"]

    body = [
        "# Run this first on Colab. Anywhere else this cell does nothing.\n",
        "#\n",
        "# Only genuinely missing packages are installed, so Colab's own versions of\n",
        "# everything it already ships are left alone.\n",
        "#\n",
        "# Generated by tools/colab_setup.py from this notebook's imports. Edit that.\n",
        "import importlib.util\n",
        "import subprocess\n",
        "import sys\n",
        "\n",
        "REQUIREMENTS = {\n",
    ]
    body += [f'    "{mod}": "{pip}",\n' for mod, pip in reqs.items()]
    body += [
        "}\n",
        "\n",
        "\n",
        "def _missing(module):\n",
        "    try:\n",
        "        return importlib.util.find_spec(module) is None\n",
        "    except ModuleNotFoundError:  # the parent package is absent\n",
        "        return True\n",
        "\n",
        "\n",
        'if "google.colab" in sys.modules:\n',
        "    need = sorted({pip for mod, pip in REQUIREMENTS.items() if _missing(mod)})\n",
        "    if need:\n",
        '        print("installing:", " ".join(need))\n',
        '        subprocess.run([sys.executable, "-m", "pip", "install", "-q", *need], check=True)\n',
        '    print("Colab setup done." if need else "Colab: nothing to install.")\n',
    ]

    return [
        {"cell_type": "markdown", "id": MD_ID, "metadata": {}, "source": md},
        {"cell_type": "code", "id": CODE_ID, "execution_count": None,
         "metadata": {}, "outputs": [], "source": body},
    ]


def with_colab_cell(cells: list[dict], out: Path) -> list[dict]:
    """Return `cells` with a current bootstrap pair as cells 1 and 2.

    Called by the lectures' build_notebook.py scripts. The pair goes after the
    title cell rather than before it, so the notebook still opens with its own
    heading in Colab and in the book.
    """
    rest = [c for c in cells if c.get("id") not in (MD_ID, CODE_ID)]
    pair = _cells({"cells": rest}, out.stem)
    return rest[:1] + pair + rest[1:]


def process(path: Path, write: bool) -> bool:
    """True if the notebook on disk already carries the current cells."""
    nb = json.loads(path.read_text())
    wanted = with_colab_cell(nb["cells"], path)
    if wanted == nb["cells"]:
        return True
    if write:
        nb["cells"] = wanted
        path.write_text(json.dumps(nb, indent=1) + "\n")
    return False


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="inject or refresh the cells")
    ap.add_argument("--check", action="store_true", help="fail if any notebook is stale")
    ap.add_argument("notebooks", nargs="*", type=Path)
    args = ap.parse_args()
    if args.write == args.check:
        ap.error("pass exactly one of --write and --check")

    # Every published notebook, which is not only the lectures: the MLOps demo
    # moved to course/optional/ with its page, and a notebook that leaves
    # lectures/ must not quietly leave the check with it.
    paths = args.notebooks or sorted(ROOT.glob("lectures/*/*.ipynb")) + sorted(
        ROOT.glob("course/optional/*.ipynb"))
    stale = [p for p in paths if not process(p, args.write)]

    for p in stale:
        print(("updated " if args.write else "STALE   ") + str(p.relative_to(ROOT)))
    if args.check and stale:
        print(f"\n{len(stale)} notebook(s) missing an up-to-date Colab cell.")
        print("Fix with: python3 tools/colab_setup.py --write")
        return 1
    print(f"{len(paths)} notebook(s) checked, {len(stale)} {'updated' if args.write else 'stale'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
