#!/usr/bin/env python3
"""Seeded per-student item selection. The Python half.

This file and game/src/seed.ts must agree byte for byte, forever. If they ever
disagree, every submitted PDF fails verification and you find out when
submissions land, not before. game/tests/vectors.json is generated by the
TypeScript side and replayed here by tools/check_vectors.py in CI, which is the
only thing standing between this design and that failure.

So: if you change anything below, change seed.ts identically, regenerate the
vectors, and let CI prove the two still agree. The order of RNG consumption is
part of the contract, not an implementation detail.

What the seeding buys, in order of value:

  1. "What did you get for number 3" stops working, which is the pedagogical
     win and the reason to do this at all.
  2. A copied PDF is detectable without any secret, because the item set is a
     function of the Andrew ID. This survives total key compromise and is the
     strongest guarantee in the whole evidence design.

What it does not buy: anything against a student who runs the module under a
classmate's ID. That forgery costs exactly as much as compliance and is
undetectable here and in Canvas. See tools/verify_evidence.py.
"""

from __future__ import annotations

import hashlib
import re
import unicodedata

# Not a secret. It ships in the JavaScript bundle, so anyone can read it.
# It is a domain separator and a between-semesters rotation knob, and describing
# it as security would be the kind of self-deception this course teaches against.
SELECTION_SALT = "f26"

_ID = re.compile(r"^[a-z][a-z0-9]{1,15}$")


def normalize_id(raw: str) -> str:
    """Canonical Andrew ID. The seed depends on this byte for byte.

    A typo here produces a PDF that fails verification for an honest student,
    which is the most likely operational failure in the whole system. The app
    echoes the normalized result back for confirmation before anything is built
    on top of it.
    """
    s = unicodedata.normalize("NFKC", raw).strip().lower()
    for suffix in ("@andrew.cmu.edu", "@cmu.edu"):
        if s.endswith(suffix):
            s = s[: -len(suffix)]
    if not _ID.match(s):
        raise ValueError(f"not a well-formed Andrew ID: {raw!r}")
    return s


def _h(*parts: bytes) -> bytes:
    """SHA-256 over NUL-separated parts.

    NUL-separated because plain concatenation is ambiguous: "ab" + "c" and
    "a" + "bc" would otherwise collide.
    """
    return hashlib.sha256(b"\x00".join(parts)).digest()


def selection_seed(andrew_id: str, lecture: str, pool_version: int) -> bytes:
    return _h(
        b"06763/select/v1",
        SELECTION_SALT.encode(),
        normalize_id(andrew_id).encode(),
        lecture.encode(),
        str(pool_version).encode(),
    )


class Rng:
    """SHA-256 in counter mode. Must be byte-identical to the one in seed.ts.

    A stream cipher rather than a small PRNG because the two implementations
    have to agree exactly, and "SHA-256 of seed || counter" is something both
    languages do the same way. mulberry32 and friends depend on 32-bit integer
    semantics that are easy to get subtly wrong across languages.
    """

    def __init__(self, seed: bytes) -> None:
        self.seed = seed
        self.ctr = 0
        self.buf = b""

    def _u32(self) -> int:
        if len(self.buf) < 4:
            # 32 is divisible by 4, so a block is consumed exactly and no bytes
            # are ever discarded. If that stops being true the two languages
            # will silently diverge.
            self.buf = hashlib.sha256(self.seed + self.ctr.to_bytes(4, "big")).digest()
            self.ctr += 1
        value = int.from_bytes(self.buf[:4], "big")
        self.buf = self.buf[4:]
        return value

    def below(self, n: int) -> int:
        """Uniform in [0, n). Rejection sampling, so no modulo bias."""
        if n <= 0:
            raise ValueError("n must be positive")
        limit = (1 << 32) // n * n
        while True:
            value = self._u32()
            if value < limit:
                return value % n

    def shuffle(self, items: list) -> list:
        out = list(items)
        for i in range(len(out) - 1, 0, -1):
            j = self.below(i + 1)
            out[i], out[j] = out[j], out[i]
        return out


def select_items(seed: bytes, pool_ids: list[str], k: int) -> list[str]:
    """Hash-and-take-lowest, not shuffle-and-slice.

    Two properties worth the extra line. It is order-independent, so reordering
    the YAML file does not reshuffle every student. And when the pool grows, one
    item is displaced rather than the whole selection being reshuffled, so
    adding a question does not invalidate PDFs already issued.
    """
    keyed = sorted(
        (hashlib.sha256(b"06763/pick/v1\x00" + seed + b"\x00" + iid.encode()).hexdigest(), iid)
        for iid in pool_ids
    )
    return [iid for _, iid in keyed[:k]]


def derive(andrew_id: str, lecture: str, pool: dict, pool_version: int, k: int) -> list[dict]:
    """The served item list: which items, which variant, which option order.

    `pool` maps item id -> item dict. The iteration order below is part of the
    contract: variant first, then option order, per item, in selection order.
    """
    seed = selection_seed(andrew_id, lecture, pool_version)
    picked = select_items(seed, sorted(pool.keys()), k)
    rng = Rng(hashlib.sha256(b"06763/order/v1\x00" + seed).digest())

    served = []
    for iid in picked:
        item = pool[iid]
        variants = item.get("variants") or [{"id": "-"}]
        variant = variants[rng.below(len(variants))]
        options = variant.get("options") or item.get("options") or []
        order = rng.shuffle(list(range(len(options)))) if options else []
        served.append({"id": iid, "variant": variant.get("id", "-"), "option_order": order})
    return served


def selection_hash(served: list[dict]) -> str:
    """Short digest of a derived list, so the verifier can compare one field."""
    blob = ";".join(
        f"{s['id']}:{s['variant']}:{','.join(map(str, s['option_order']))}" for s in served
    )
    return hashlib.sha256(b"06763/selhash/v1\x00" + blob.encode()).hexdigest()[:16]
